### ISSUE TITLE
Building the website libcgl.tech

### ISSUE THREAD

**Issue by Jaysmito101** [Jaysmito101/cgl#10]
Build the project website to host example docs. 
Development is being done under website branch.

**Comment by Mr-Sunglasses** [comment]
@Jaysmito101 In website we just need to show the documentation of the project. So can we use documentation generation tools like [Sphinx](https://www.sphinx-doc.org/) to generate that. If you allow me I would love to work on this issue 😊.

**Comment by Jaysmito101** [comment]
@Mr-Sunglasses using something like that won't do as the website will not only host the docs but also examples like https://youtube.com/shorts/c78KkAZhkaQ?feature=share somewhat like what shadertoy.com does it.
