### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by utkarsh006** [Jaysmito101/cgl#13]
- The README file is too large and hard to understand in one go.
- Will make the file concise and easier to read.
- Contributing under KWOC'22.

**Comment by utkarsh006** [comment]
@Jaysmito101 I won't be removing any information from the file but would make it concise through proper documentation.

**Comment by Jaysmito101** [comment]
Alright make the relevant pull request I will check it out.

**Comment by utkarsh006** [comment]
@Jaysmito101 Yes do assign me the issue !

**Comment by Jaysmito101** [comment]
Fixed by #14
