### ISSUE TITLE
Feature Request: Extend Matrix Library for mXn matrix math

### ISSUE THREAD

**Issue by Jaysmito101** [Jaysmito101/cgl#23]

**Comment by Atul-8115** [comment]
I want to work on this issue please assign it to me

**Comment by purbakundu** [comment]
i want to contribute

**Comment by Codey001** [comment]
i want to work on the issue

**Comment by Michael-G-Scott** [comment]
I want to work on this issue

**Comment by Jaysmito101** [comment]
@Atul-8115 I am assuming this to you first.

**Comment by Jaysmito101** [comment]
@Atul-8115 since you werent able to solve this within 2 days, I am assigning this to @purbakundu .
@purbakundu you have 2 days to solve this.

**Comment by Jaysmito101** [comment]
Those working on this please check this commit and build on top of that https://github.com/Jaysmito101/cgl/commit/b4c5e12b988714fa16255dfe3f15a7b7ac6080e2
