### ISSUE TITLE
Feature Request: Implement Generic Quick Sort & Merge Sort

### ISSUE THREAD

**Issue by Jaysmito101** [Jaysmito101/cgl#26]
Implement quick sort and merge sort for general data in CGL style.

**Comment by Sindhu-2004** [comment]
Can i work on this issue
I will try my best to solve this issue, eventhough i am not familiar with this sir

**Comment by SoumyadeepOSD** [comment]
@Jaysmito101  Can You Assign this issue to me? I'll try to solve this issue

**Comment by Jaysmito101** [comment]
@Sindhu-2004 I will assign this to you first. 
@SoumyadeepOSD if @Sindhu-2004 isnt able to finish this within 24 hours i will assign this to you.

**Comment by Sindhu-2004** [comment]
Ok thank you

**Comment by Jaysmito101** [comment]
@SoumyadeepOSD I am assigning this issue to you. You have 1 day for this.
