### ISSUE TITLE
Hey there I want to work on this issue.

### ISSUE THREAD

**Issue by sonukmrsah** [Jaysmito101/cgl#28]
hey! I want to work on this issue.

**Comment by Jaysmito101** [comment]
@sonukmrsah either choose an existing issue or create a relevant issue explaining what you are interested in contributing.

**Comment by sonukmrsah** [comment]
I want to fix typos or readme fixes basically it will be a non code contribution!

**Comment by Jaysmito101** [comment]
@sonukmrsah in that case whether or not your contribution will be accepted depends on the effort put in. We are currently not accepting very small non code fixes.

**Comment by sonukmrsah** [comment]
No problem!
