### ISSUE TITLE
update the readme

### ISSUE THREAD

**Issue by Code1705** [Jaysmito101/cgl#31]
proper documentation about contribution guidelines and many important points , please assign me under JWOC.

**Comment by Jaysmito101** [comment]
@Code1705  Could you please elaborate. Also its better if you could give some examples.

**Comment by Code1705** [comment]
Like documentation about the open source contribution process and emojis and mention the project  maintainer and what improvement to be done to make it a better project

**Comment by Code1705** [comment]
to make it interesting , presentable attractive certain elements  and  project maintainer rights point is also not mentioned , please assign me under JWOC.
