### ISSUE TITLE
Hindi Readme for multilinguals

### ISSUE THREAD

**Issue by A91y** [Jaysmito101/cgl#32]
New Readme can be written in Hindi to help multilinguals.

**Comment by A91y** [comment]
Please assign me this issue under iwoc and easy/medium/hard.

**Comment by Jaysmito101** [comment]
@A91y Alright.

**Comment by A91y** [comment]
@Jaysmito101 please add iwoc instead of jwoc tag

**Comment by onlyVishesh** [comment]
Please assign me this issue. I can solve it
